paths:
    file_path: "E:\\2025 work streams\\caf.brAIn\\prediction_model\\model_review\\cb_tfn_v15.csv"
    folder_path: null
    output_path: "E:\\2025 work streams\\caf.brAIn\\prediction_model\\model_review"
    validation_path: null

data_classification:
    target_column: "numcarvan"
    custom_index:
        - "householdid"
        - "surveyyear"
        - "hholdua_b01id"
    categorical_features:
        - "tfn_at"
        - "hh_child"
        - "ns"
        - "hholdnumadults"
    numerical_features:
        - "hh_income"
    weight_column: "w2"
    is_time_series: True

transforming_inputs:
    column_name_to_drop_rows: null
    value_in_row: null
    classification_prediction: [0, 1, 2]
    split_by_value: null
    split_size: 0.2
    sample_size_encode: False
    select_encode_values: False
    encode_values_to_drop: null

modelling:
    model_choice:
        - LOGIT_REGRESSION_ELASTICNET
        - RANDOM_FOREST_CLASSIFIER
    full_transformations: True
    cv: null
    skip_feature_selection: False
    intensive_feature_selection: False
