file_path: "E:\\2025 work streams\\redo_cafml\\cb_tfn_v15.csv"
folder_path: null
output_path: "E:\\2025 work streams\\caf.brAIn\\prediction_model\\final_testing"
validation_path: null

target_column: "numcarvan"
custom_index:
  - "householdid"
  - "surveyyear"
  - "hholdua_b01id"
column_name_to_drop_rows:
  - "tfn_at"
value_in_row:
  - "20"

categorical_features:
  - "tfn_at"
  - "hh_child"
  - "ns"
  - "hholdnumadults"
numerical_features:
  - "hh_income"
  - "trips"
weight_column: "w2"
classification_prediction: [0, 1]
split_by_value: null
split_size: 0.2
sample_size_encode: False
select_encode_values: False
encode_values_to_drop: null

model_choice: LOGIT_REGRESSION_ELASTICNET
is_time_series: False
full_transformations: True
cv: "kfold"
skip_feature_selection: False
intensive_feature_selection: False
