output_path: Optional[Path] = None
image_folder_path: Optional[Path] = None
satellite_image_metadata: Optional[Path] = None
user_locations_path: Optional[Path] = None
x_coordinate: Optional[str] = None
y_coordinate: Optional[str] = None
class_names: Optional[list[str]] = None
hyperparameter_optimisation: Optional[str] = None
prediction_images_folder: Optional[Path] = None
