# Most basic config run possible

output_path: "E:\\2025 work streams\\caf.brAIn\\machine vision\\generate_training_images_test"
generate_training_images: True
training_data_information: null
noham_path: "E:\\2025 work streams\\caf.brAIn\\machine vision\\NN input data\\04.Final Base Network\\NoHAM_Base.DBF"
geo_path: "E:\\2025 work streams\\caf.brAIn\\machine vision\\NN input data\\test\\NoHAM_Base_node.shp"  #"E:\\2025 work streams\\caf.brAIn\\machine vision\\NN input data\\test"
image_folder_path: "B:\\North England\\RGB_12.5cm"
final_html_info: null
x_column: null
y_column: null
