"""
Generate a custom object detection model using BNG BlueSky satellite images.
Generate satellite images allows you to generate training images based on bng
coordinate locations. Train object detection model allows you to train a yolo
model based on the images. The main function lets you run inference on the
trained model.
"""

# Built-Ins
import logging
import os
import time
import warnings
from pathlib import Path
from typing import Optional

# Third Party
import pandas as pd
from caf.toolkit import BaseConfig

# Local Imports
from caf.brain.object_detection import crop_user_images as crop
from caf.brain.object_detection import geographic_metadata as geo_meta
from caf.brain.object_detection import inference
from caf.brain.object_detection import satellite_img_metadata as img_meta
from caf.brain.object_detection import user_img_metadata as user_meta
from caf.brain.object_detection.model_building import build, build_data

LOG = logging.getLogger(__name__)
IMAGE_METADATA = Path(
    os.getenv(
        "CAF_BRAIN_IMAGE_METADATA", r"B:\TfN_object_detection\satellite_image_metadata.csv"
    )
)
_PRE_TRAINED_MODEL_DEFAULT = Path(r"B:\TfN_object_detection\best.pt")


class PredictionInputs(BaseConfig):
    """
    Object detection inputs that are paths to external files.
    """

    user_location: Optional[Path | str] = None
    output_path: Optional[Path] = None
    image_folder_path: Optional[Path] = None
    model_path: Optional[Path] = None


class ObjectDetectionInputs(BaseConfig):
    """
    Caf.brAIn object detection model inputs.
    """

    object_detection: PredictionInputs = PredictionInputs()


def generate_satellite_images(
    user_location: Path | str,
    output_path: Path | str,
    image_folder_path: Path | str,
    metadata_path: Path = IMAGE_METADATA,
) -> Path:
    """
    Generates satellite images for YOLO modelling.

    Parameters
    ----------
    user_location:
        A path to a shapefile with a geometry column or x and y columns. These
        are the locations of where you want to predict. If you are conducting
        junction detection, a string of a LSOA, LAD or British town / city can
        be provided (See "B:/TfN_object_detection/Towns_and_Cities" for
        available cities). All junction locations in that area will be identified.
    image_folder_path:
        Path to TfN image folder (B drive connection). Specifically the high
        level folder that houses the region folder ("B:/England 12.5cm").
    output_path:
        Path to save the generated images to.
    metadata_path:
        Path to satellite images metadata that is generated by image_info_generation.
        image_info_generation is called by this function unless a path is
        provided.

    Returns
    -------
    Location of saved processed images.
    """
    LOG.info("Generating satellite images")

    output_path = Path(output_path)
    image_folder_path = Path(image_folder_path)

    model_dir = Path(output_path) / "caf.brAIn_image_generation"
    model_dir.mkdir(parents=True, exist_ok=True)

    if metadata_path.exists():
        satellite_image_metadata = pd.read_csv(metadata_path)
    else:
        satellite_image_metadata = img_meta.image_info_generation(
            output_path=model_dir,
            image_folder_path=image_folder_path,
        )

    df = geo_meta.generate_user_location_shp_file(
        output_path=model_dir,
        user_prediction_location=user_location,
    )

    user_image_metadata = user_meta.locate_user_coordinates(
        df=df,
        output_path=model_dir,
        satellite_image_metadata=satellite_image_metadata,
        image_folder_path=image_folder_path,
    )

    output_dir = crop.image_crop(
        user_image_metadata=user_image_metadata,
        output_path=model_dir,
        satellite_image_metadata=satellite_image_metadata,
    )
    return output_dir


def train_object_detection_model(
    user_image_folder_path: Path | str,
    class_names: list[str],
    output_path: Path | str,
) -> None:
    """
    Train a YOLO object detection model.

    Requires images generated by generate_satellite_images. These images should
    be labelled with YOLO formatting:
    - Text file for every image
    - Text file format: <class_id> <x_centre> <y_centre> <width> <height>

    Parameters
    ----------
    user_image_folder_path:
        Path to folder of user images.
    class_names:
        Classification names in the order they were labelled in.
    output_path:
        Path to save the generated images to.

    Returns
    -------
    None
    """
    LOG.info("Building object detection model.")
    warnings.warn(
        "It is advised to use a GPU machine to train your model "
        "otherwise the model training process will use your machines"
        "entire capability and can take multiple days."
    )
    start_time = time.time()

    user_image_folder_path = Path(user_image_folder_path)
    output_path = Path(output_path)

    warnings.warn(
        f"TfN trained model already exists here: {_PRE_TRAINED_MODEL_DEFAULT}. Please stop the function and use this as your model if you're doing junction detection only."
    )

    results = build_data.count_valid_pairs(folder_path=user_image_folder_path)
    valid_pairs = results["valid_pairs"]
    if valid_pairs >= 1200:
        model_dir = Path(output_path) / "caf.brAIn_model_building"
        model_dir.mkdir(parents=True, exist_ok=True)

        train_path = model_dir / "train"
        test_path = model_dir / "test"
        val_path = model_dir / "val"

        train, test, validation = build_data.main_ttv_creation(
            user_images_folder_path=user_image_folder_path,
            output_path=model_dir,
        )

        build_data.generate_folders(dictionary=train, folder_name="train", output=model_dir)
        build_data.generate_folders(dictionary=test, folder_name="test", output=model_dir)
        build_data.generate_folders(dictionary=validation, folder_name="val", output=model_dir)

        build_data.ensure_labels(folder_path=train_path)
        build_data.ensure_labels(folder_path=test_path)
        build_data.ensure_labels(folder_path=val_path)

        build_data.build_config(
            output=model_dir,
            class_names=class_names,
        )

        build.main_model_build(
            output=model_dir,
            hyperparameter_optimisation="base",
        )
    else:
        raise ValueError(
            f"Not enough training images with valid pairs provided. "
            f"You provided {valid_pairs} but at least 1200 are required."
        )

    end_time = time.time()
    LOG.info("Total run time: %.2f seconds", end_time - start_time)
    LOG.info("Finished model build")


def main(
    params: ObjectDetectionInputs,
    output_path: Path | str,
) -> None:
    """
    Main object detection prediction function.

    Use this function to predict on satellite images if a model path is provided.
    If no model path is provided, it is assumed that you are conducting
    junction detection with TfNs saved model B:/TfN_object_detection/best.pt.

    Parameters
    ----------
    params:
        Config file inputs
    output_path:
        Path to output file location. Should be generated during model setup
        if not passed directly.

    Returns
    -------
    None
    """
    LOG.info("Building object detection model.")

    if params.object_detection.model_path is None:
        raise ValueError(
            "Model path must be provided. To generate this, either \n"
            "run the train_object_detection_model or if doing junction \n"
            "detection, use the TfN model here: B:/TfN_object_detection/best.pt"
        )

    output_path = Path(output_path)

    if params.object_detection.user_location is None:
        raise ValueError("user_location cannot be None.")

    if params.object_detection.image_folder_path is None:
        raise ValueError("image_folder_path cannot be None.")
    image_folder_path = Path(params.object_detection.image_folder_path)

    model_path = Path(params.object_detection.model_path)

    start_time = time.time()

    LOG.info(
        "Generate_satellite_images has to be run in order to generate images for prediction."
    )
    output_dir = generate_satellite_images(
        user_location=params.object_detection.user_location,
        output_path=output_path,
        image_folder_path=image_folder_path,
    )

    inference.main_prediction(
        output=output_path,
        images_to_predict_path=output_dir,
        model_path=model_path,
    )

    end_time = time.time()
    LOG.info("Total run time: %.2f seconds", end_time - start_time)
    LOG.info("Finished model build")
