"""Created on: 25/02/2026 Original author: Adil Zaheer"""

# Built-Ins
import logging
import os
import time
from pathlib import Path

# Third Party
import pandas as pd

# Local Imports
from caf.brain.object_detection._functions.crop_user_satellite_images.main import (
    image_crop,
)
from caf.brain.object_detection._functions.generate_satellite_image_information.main import (
    image_info_generation,
)
from caf.brain.object_detection._functions.generate_set_geog_data.functions import (
    generate_user_location_shp_file,
)
from caf.brain.object_detection._functions.generate_user_image_metadata.main import (
    locate_user_coordinates,
)
from caf.brain.object_detection._functions.model_building.build_model_data_functions import (
    build_config,
    count_valid_pairs,
    ensure_labels,
    generate_folders,
    main_ttv_creation,
)
from caf.brain.object_detection._functions.model_building.main import (
    main_model_build,
)

LOG = logging.getLogger(__name__)
IMAGE_METADATA = Path(
    os.getenv(
        "CAF_BRAIN_IMAGE_METADATA", r"B:\TfN_object_detection\satellite_image_metadata.csv"
    )
)
_PRE_TRAINED_MODEL_DEFAULT = Path(r"B:\TfN_object_detection\best.pt")


def generate_satellite_images(
    user_location: Path | str,
    output_path: Path | str,
    image_folder_path: Path | str,
    metadata_path: Path = IMAGE_METADATA,
) -> Path:
    """
    Generates satellite images for YOLO modeling.

    Parameters
    ----------
    user_location:
        A path to a shapefile with a geometry column or x and y columns. These
        are the locations of where you want to predict. If you are conducting
        junction detection, a string of a LSOA, LAD or British town / city can
        be provided (See "B:/TfN_object_detection/Towns_and_Cities" for
        available cities). All junction locations in that area will be identified.
    image_folder_path:
        Path to TfN image folder (B drive connection). Specifically the high
        level folder that houses the region folder ("B:/England 12.5cm").
    output_path:
        Path to save the generated images to.
    metadata_path:
        Path to satellite images metadata that is generated by image_info_generation.
        image_info_generation is called by this function unless a path is
        provided.

    Returns
    -------
    Location of saved processed images.
    """
    LOG.info("Generating satellite images")

    output_path = Path(output_path)
    image_folder_path = Path(image_folder_path)

    model_dir = Path(output_path) / "caf.brAIn_image_generation"
    model_dir.mkdir(parents=True, exist_ok=True)

    if metadata_path.exists():
        satellite_image_metadata = pd.read_csv(metadata_path)
    else:
        satellite_image_metadata = image_info_generation(
            output_path=model_dir,
            image_folder_path=image_folder_path,
        )

    df = generate_user_location_shp_file(
        output_path=model_dir,
        user_prediction_location=user_location,
    )

    user_image_metadata = locate_user_coordinates(
        df=df,
        output_path=model_dir,
        satellite_image_metadata=satellite_image_metadata,
        image_folder_path=image_folder_path,
    )

    output_dir = image_crop(
        user_image_metadata=user_image_metadata,
        output_path=model_dir,
        satellite_image_metadata=satellite_image_metadata,
    )
    return output_dir


def train_object_detection_model(
    user_image_folder_path: Path | str,
    class_names: list[str],
    output_path: Path | str,
) -> None:
    """
    Train a YOLO object detection model.

    Requires images generated by generate_satellite_images. These images should
    be labeled with YOLO formatting:
    - Text file for every image
    - Text file format: <class_id> <x_center> <y_center> <width> <height>

    Parameters
    ----------
    user_image_folder_path:
        Path to folder of user images.
    class_names:
        Classification names in the order they were labeled in.
    output_path:
        Path to save the generated images to.

    Returns
    -------
    None
    """
    LOG.info("Building object detection model.")
    LOG.warning(
        "It is advised to use a GPU machine to train your model "
        "otherwise the model training process will use your machines"
        "entire capability and can take multiple days."
    )
    start_time = time.time()

    user_image_folder_path = Path(user_image_folder_path)
    output_path = Path(output_path)

    LOG.warning(
        "TfN trained model already exists here: %s. Please stop the function and use this as your model if you're doing junction detection only.",
        _PRE_TRAINED_MODEL_DEFAULT,
    )

    results = count_valid_pairs(folder_path=user_image_folder_path)
    valid_pairs = results["valid_pairs"]
    if valid_pairs >= 1200:
        model_dir = Path(output_path) / "caf.brAIn_model_building"
        model_dir.mkdir(parents=True, exist_ok=True)

        train_path = model_dir / "train"
        test_path = model_dir / "test"
        val_path = model_dir / "val"

        train, test, validation = main_ttv_creation(
            user_images_folder_path=user_image_folder_path,
            output_path=model_dir,
        )

        generate_folders(dictionary=train, folder_name="train", output=model_dir)
        generate_folders(dictionary=test, folder_name="test", output=model_dir)
        generate_folders(dictionary=validation, folder_name="val", output=model_dir)

        ensure_labels(folder_path=train_path)
        ensure_labels(folder_path=test_path)
        ensure_labels(folder_path=val_path)

        build_config(
            output=model_dir,
            class_names=class_names,
        )

        main_model_build(
            output=model_dir,
            hyperparameter_optimisation="base",
        )
    else:
        raise ValueError(
            "Not enough training images with valid pairs provided \
             You provided %s but at least 1200 are required",
            valid_pairs,
        )

    end_time = time.time()
    LOG.info("Total run time: %.2f seconds", end_time - start_time)
    LOG.info("Finished model build")
