"""Generate metadata that is used to guide the processing of satellite images
inline with the user specifications."""

# Built-Ins
import glob
import logging
import os
from pathlib import Path

# Third Party
import geopandas as gpd
import numpy as np
import pandas as pd
from scipy.spatial.distance import cdist
from tqdm import tqdm

LOG = logging.getLogger(__name__)


def _euclidean_distance(df_a: pd.DataFrame, df_b: pd.DataFrame) -> pd.DataFrame:
    """
    Calculate the Euclidean distance.

    Distance between the user provided locations and the center points of the
    British National Grid tiles.

    Parameters
    ----------
    df_a:
        Satellite image metadata dataframe generated by image_info_generation.
    df_b:
        User coordinate dataframe with a coordinates_easting and
        coordinates_northing column.

    Returns
    -------
    result_df:
        Users input dataframe with the name of the closest British National
        Grid image tile.
    """
    coords_a = df_a[["tile_easting", "tile_northing"]].values
    coords_b = df_b[["coordinates_easting", "coordinates_northing"]].values

    distances = cdist(coords_b, coords_a, metric="euclidean")

    closest_indices = np.argmin(distances, axis=1)
    closest_boundaries = df_a.iloc[closest_indices]["box_boundary"].values

    result_df = df_b.copy()
    result_df["box_boundary"] = closest_boundaries

    result_df["box_boundary"] = result_df["box_boundary"].astype(str)

    return result_df


def _user_image_path_finder(
    image_folder: Path, user_coordinate_data: pd.DataFrame
) -> pd.DataFrame:
    """
    Find image paths for each of the user provided coordinates.

    Each row in user_coordinate_data has a box_boundary identifier.
    This function searches the image folder (recursively) for .jpg files
    whose filename (without extension) matches one of those identifiers.

    Parameters
    ----------
    image_folder:
        Path to image folder.
    user_coordinate_data:
        User coordinate data created after the euclidean_distance function.

    Returns
    -------
    path_df:
        Satellite image path dataframe that corresponds to the user provided
        locations.
    """

    counter = 0
    paths = glob.glob(os.path.join(image_folder) + "/**/*.jpg", recursive=True)

    user_coordinate_data["box_boundary"] = user_coordinate_data["box_boundary"].astype(str)
    reference_set = set(user_coordinate_data["box_boundary"].values)

    path_dict = {}
    LOG.info(
        "Looking for %s unique reference values in %s image files",
        len(reference_set),
        len(paths),
    )

    with tqdm(total=len(paths)) as pbar:
        for path in paths:
            _, file_name = os.path.split(path)
            name = os.path.splitext(file_name)[0]

            if name in reference_set:
                path_dict[name] = path
            pbar.update(1)
            counter += 1
            if counter % 100 == 0:
                LOG.info(
                    "Processed %s/%s paths, found %s matches so far",
                    counter,
                    len(paths),
                    len(path_dict),
                )

    path_df = pd.DataFrame(list(path_dict.items()), columns=["box_boundary", "paths"])

    return path_df


def locate_user_coordinates(
    df: gpd.GeoDataFrame,
    output_path: Path,
    satellite_image_metadata: pd.DataFrame,
    image_folder_path: Path,
) -> pd.DataFrame:
    """
    Locate the satellite images that correspond to user input coordinates.

    Parameters
    ----------
    df:
        gpd.GeoDataFrame that contains user coordinates.
    output_path:
        Path to output folder.
    satellite_image_metadata:
        Satellite image metadata containing tile names, midpoints and path
        locations. Generated from image_info_generation.
    image_folder_path:
        Path to folder that contains British National Grid tile jpegs and
        their accompanying XML files.

    Returns
    -------
    user_image_metadata:
        Dataframe with user coordinate locations, relevant classification and
        location specific satellite metadata.
    """
    output_path = Path(output_path)
    image_folder_path = Path(image_folder_path)

    df["coordinates_easting"] = df["geometry"].x
    df["coordinates_northing"] = df["geometry"].y

    user_data_with_closest_tile = _euclidean_distance(df_a=satellite_image_metadata, df_b=df)

    path_df = _user_image_path_finder(
        image_folder=image_folder_path, user_coordinate_data=user_data_with_closest_tile
    )

    user_image_metadata = pd.merge(
        user_data_with_closest_tile, path_df, on="box_boundary", how="inner"
    )

    user_coordinate_filename = output_path / "user_coordinate_data.csv"
    user_image_metadata.to_csv(user_coordinate_filename, index=False)

    return user_image_metadata
