"""
Created on: 9/25/2025
Original author: Adil Zaheer
"""

# Built-Ins
import glob
import logging
import os
from pathlib import Path

# Third Party
import geopandas as gpd
import numpy as np
import pandas as pd
from scipy.spatial.distance import cdist
from tqdm import tqdm

LOG = logging.getLogger(__name__)


def _find_file_type(file_path: Path) -> str | None:
    """
    Helper function for finding file types.

    Parameters
    ----------
    file_path:
        Path to file.

    Returns
    -------
    String with file ending e.g. csv, shp or None.
    """
    _, ext = os.path.splitext(file_path)
    ext = ext.lower()

    if ext == ".csv":
        return "csv"
    if ext == ".shp":
        return "shp"
    return None


def _read_path(file_path: Path):
    """
    Function to read in files based on their file types.

    Parameters
    ----------
    file_path:
        Path to file.

    Returns
    -------
    Either a dataframe or geo-dataframe of your data along with their file
    type.
    """
    file_type = _find_file_type(file_path)
    if file_type == "csv":
        df = pd.read_csv(file_path)
        return df, file_type
    if file_type == "shp":
        gdf = gpd.read_file(file_path)
        return gdf, file_type
    raise ValueError("Unsupported file type.")


def _euclidean_distance(df_a: pd.DataFrame, df_b: pd.DataFrame) -> pd.DataFrame:
    """
    Calculate the Euclidean distance.

    Distance between the user provided locations and the center points of the
    British National Grid tiles.

    Parameters
    ----------
    df_a:
        Satellite image metadata dataframe generated by image_info_generation.
    df_b:
        User coordinate dataframe with a coordinates_easting and
        coordinates_northing column.

    Returns
    -------
    result_df:
        Users input dataframe with the name of the closest British National
        Grid image tile.
    """
    coords_a = df_a[["tile_easting", "tile_northing"]].values
    coords_b = df_b[["coordinates_easting", "coordinates_northing"]].values

    distances = cdist(coords_b, coords_a, metric="euclidean")

    closest_indices = np.argmin(distances, axis=1)
    closest_boundaries = df_a.iloc[closest_indices]["box_boundary"].values

    result_df = df_b.copy()
    result_df["box_boundary"] = closest_boundaries

    result_df["box_boundary"] = result_df["box_boundary"].astype(str)

    return result_df


def _user_image_path_finder(
    image_folder: Path, user_coordinate_data: pd.DataFrame
) -> pd.DataFrame:
    """
    Find image paths for each of the user provided coordinates.

    Each row in user_coordinate_data has a box_boundary identifier.
    This function searches the image folder (recursively) for .jpg files
    whose filename (without extension) matches one of those identifiers.

    Parameters
    ----------
    image_folder:
        Path to image folder.
    user_coordinate_data:
        User coordinate data created after the euclidean_distance function.

    Returns
    -------
    path_df:
        Satellite image path dataframe that corresponds to the user provided
        locations.
    """

    counter = 0
    paths = glob.glob(os.path.join(image_folder) + "/**/*.jpg", recursive=True)

    user_coordinate_data["box_boundary"] = user_coordinate_data["box_boundary"].astype(str)
    reference_set = set(user_coordinate_data["box_boundary"].values)

    path_dict = {}
    LOG.info(
        "Looking for %s unique reference values in %s image files",
        len(reference_set),
        len(paths),
    )

    with tqdm(total=len(paths)) as pbar:
        for path in paths:
            _, file_name = os.path.split(path)
            name = os.path.splitext(file_name)[0]

            if name in reference_set:
                path_dict[name] = path
            pbar.update(1)
            counter += 1
            if counter % 100 == 0:
                LOG.info(
                    "Processed %s/%s paths, found %s matches so far",
                    counter,
                    len(paths),
                    len(path_dict),
                )

    path_df = pd.DataFrame(list(path_dict.items()), columns=["box_boundary", "paths"])

    return path_df
