paths:
    file_path: null
    folder_path: null
    output_path: null
    validation_path: null

data_classification:
    target_column: null
    custom_index:
      - null
    categorical_features:
        - null
    numerical_features:
        - null
    weight_column: null
    is_time_series: False

transforming_inputs:
    column_name_to_drop_rows:
      - null
    value_in_row:
      - null
    classification_prediction: null
    split_by_value: null
    split_size: null
    sample_size_encode: False
    select_encode_values: False
    encode_values_to_drop: null

modelling:
    model_choice:
        - null
    full_transformations: False
    cv: null
    skip_feature_selection: False
    intensive_feature_selection: False

